version: "3.9"

services:
  init-fs:
    image: busybox:1.36
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    command: >
      sh -eu -c '
        mkdir -p /host/static /host/media &&
        chown -R "$UID:$GID" /host/static /host/media &&
        chmod -R u+rwX,go+rX /host/static /host/media
      '
    volumes:
      - /var/www/pierreandrieu/static:/host/static:rw
      - /var/www/pierreandrieu/media:/host/media:rw
    restart: "no"

  db:
    image: postgres:16
    env_file: .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }
    security_opt: [ "no-new-privileges:true" ]

  web:
    build: .
    env_file: .env.prod
    environment:
      ENVIRONMENT: production
      DJANGO_SETTINGS_MODULE: sitepro.settings.prod
      MEDIA_ROOT: /app/media
    depends_on:
      init-fs:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    volumes:
      - /var/www/pierreandrieu/static:/app/staticfiles:ro
      - /var/www/pierreandrieu/media:/app/media:ro
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }

    healthcheck:
      test: [ "CMD", "python", "-c", "import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8000)); s.close()" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    read_only: true
    tmpfs: [ "/tmp" ]
    security_opt: [ "no-new-privileges:true" ]
    cap_drop: [ "ALL" ]
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 2g

volumes:
  postgres_data:
