services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: sitepro.settings.dev
    env_file:
      - .env.dev
    volumes:
      - .:/app
    tty: true
